/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommentCreate: typeof import('./../../src/views/posts/components/CommentCreate.vue')['default']
    CommentItem: typeof import('./../../src/views/posts/components/CommentItem.vue')['default']
    CommentList: typeof import('./../../src/views/posts/components/CommentList.vue')['default']
    Compute: typeof import('./../../src/components/Compute.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    Icon: typeof import('./../../src/features/platform/icons/components/Icon.vue')['default']
    Modals: typeof import('./../../src/features/platform/modals/components/Modals.vue')['default']
    PostCard: typeof import('./../../src/views/posts/components/PostCard.vue')['default']
    PostDetailSkeleton: typeof import('./../../src/views/posts/components/PostDetailSkeleton.vue')['default']
    PostFilters: typeof import('./../../src/views/posts/components/PostFilters.vue')['default']
    PostFormModal: typeof import('./../../src/views/posts/components/PostFormModal.vue')['default']
    PostSkeleton: typeof import('./../../src/views/posts/components/PostSkeleton.vue')['default']
    PostSortSelect: typeof import('./../../src/views/posts/components/PostSortSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./../../src/views/posts/components/SearchInput.vue')['default']
  }
}
