/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Compute: typeof import('./../../src/components/Compute.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    HomeComponent: typeof import('./../../src/views/home/components/HomeComponent.vue')['default']
    HomeModal: typeof import('./../../src/views/home/components/modals/HomeModal.vue')['default']
    HomeNestedComponent: typeof import('./../../src/views/home/components/nested/HomeNestedComponent.vue')['default']
    Icon: typeof import('./../../src/features/platform/icons/components/Icon.vue')['default']
    Modals: typeof import('./../../src/features/platform/modals/components/Modals.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
